CREATE DATABASE MATRICULA
USE MATRICULA

CREATE TABLE ALUMNO(
ID_ALUMNO INT AUTO_INCREMENT PRIMARY KEY,
DNI_ALUMNO CHAR(8) UNIQUE NOT NULL,
NOMBRES VARCHAR (50) NOT NULL,
APELLIDOS VARCHAR (50) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
EDAD INT NOT NULL,
GENERO CHAR (1),
DIRECCION VARCHAR(100) NOT NULL,
CELULAR CHAR (9) NOT NULL,
CORREO VARCHAR (80) UNIQUE NOT NULL,
NOMBRE_APODERADO VARCHAR(50) NULL,
CELULAR_APODERADO CHAR(9) NULL,
USERNAME VARCHAR (50) UNIQUE NOT NULL,
PASSWORD_HASH VARCHAR (255) NOT NULL,
ESTADO VARCHAR(50) NOT NULL DEFAULT 'Inactivo',
FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE AULA(
ID_AULA INT AUTO_INCREMENT PRIMARY KEY,
NIVEL VARCHAR(30) NOT NULL,
GRADO INT NOT NULL,
SECCION CHAR (1) NOT NULL,
VACANTES_TOTALES INT NOT NULL,
VACANTES_DISPONIBLES INT NOT NULL
);

CREATE TABLE RESERVA(
ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
ID_ALUMNO INT NOT NULL,
ID_AULA INT NOT NULL,
CODIGO_PAGO VARCHAR(20) UNIQUE NOT NULL,
FECHA_RESERVA DATETIME DEFAULT CURRENT_TIMESTAMP,
ESTADO_PAGO VARCHAR(20) DEFAULT 'PENDIENTE'
);

-- RELACIONES ENTRE TABLAS
ALTER TABLE reserva
ADD CONSTRAINT FK_RELACION1
FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO (ID_ALUMNO);

ALTER TABLE reserva
ADD CONSTRAINT FK_RELACION2
FOREIGN KEY (ID_AULA) REFERENCES AULA (ID_AULA); 

INSERT INTO aula (nivel, grado, seccion, vacantes_totales, vacantes_disponibles)
VALUES
('Secundaria', 3, 'A', 30, 5),
('Secundaria', 3, 'B', 30, 0),
('PRIMARIA', 1, 'A', 25, 25),
('PRIMARIA', 1, 'B', 30, 12);

SELECT * FROM aula;

CREATE TABLE USUARIO(
ID INT AUTO_INCREMENT PRIMARY KEY,
USERNAME VARCHAR(50) UNIQUE NOT NULL,
PASSWORD_HASH VARCHAR(200) NOT NULL,
ESTADO TINYINT (1) DEFAULT 1
);

INSERT INTO USUARIO (USERNAME, PASSWORD_HASH)
VALUES('Admin','$2y$10$heuMG7aElXF5IiS4rCN49.T.smRQfhlCmVuoAh/SPpjQ6YA6qzZO6');

SELECT * FROM USUARIO

SELECT * FROM ALUMNO

INSERT INTO ALUMNO (DNI_ALUMNO, NOMBRES, APELLIDOS, FECHA_NACIMIENTO, EDAD, GENERO, DIRECCION, CELULAR, CORREO, NOMBRE_APODERADO, CELULAR_APODERADO, USERNAME, PASSWORD_HASH, ESTADO) 
VALUES (
    '47350997', 'Nikola', 'Tesla', '2006-05-15', 20, 'M', 'Av. peru','939429147', 'tesla@gmail.com','sonia', '939429147','nikola.tesla', 'mundo', 'Activo'
	);


CREATE TABLE CURSO(
    ID_CURSO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_CURSO VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(30) NULL,
    NIVEL VARCHAR(30) NOT NULL,
    GRADO INT NOT NULL,
    HORAS_SEMANALES INT NOT NULL,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'Activo'
);

INSERT INTO CURSO (NOMBRE_CURSO, DESCRIPCION, NIVEL, GRADO, HORAS_SEMANALES, ESTADO)
VALUES
('Matemática Base', 'Aritmética', 'Primaria', 1, 4, 'Activo'),
('Comunicación', 'Lectura', 'Primaria', 1, 4, 'Activo'),
('Ciencias', 'Ciencias Naturales', 'Primaria', 1, 2, 'Activo'),
('Matemática', 'Trigonometría', 'Secundaria', 3, 4, 'Activo'),
('Historia', 'Historia del Perú', 'Secundaria', 3, 2, 'Inactivo');


CREATE TABLE MATRICULA (
    ID_MATRICULA INT AUTO_INCREMENT PRIMARY KEY,
    ID_ALUMNO INT NOT NULL,
    ID_CURSO INT NOT NULL,
    FECHA_MATRICULA DATE NOT NULL,
    ANIO_ESCOLAR YEAR NOT NULL,
    TURNO VARCHAR (20) NOT NULL,
    ESTADO VARCHAR (20) DEFAULT 'Pendiente',
    OBSERVACIONES TEXT,
    FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO(ID_ALUMNO),
    FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)
);

CREATE TABLE PAGO (
    ID_PAGO         INT AUTO_INCREMENT PRIMARY KEY,
    ID_MATRICULA    INT NOT NULL,
    CONCEPTO        VARCHAR(100) NOT NULL,
    MONTO           DECIMAL(10,2) NOT NULL,
    FECHA_PAGO      DATE NOT NULL,
    METODO_PAGO     VARCHAR(20) NOT NULL,
    ESTADO          VARCHAR(20) DEFAULT 'Pendiente',
    OBSERVACIONES   TEXT,
    FOREIGN KEY (ID_MATRICULA) REFERENCES MATRICULA(ID_MATRICULA)
);

CREATE TABLE CONFIGURACION (
    ID_CONFIG   INT AUTO_INCREMENT PRIMARY KEY,
    CLAVE       VARCHAR(50) UNIQUE NOT NULL,
    VALOR       VARCHAR(255) NOT NULL
);

INSERT INTO CONFIGURACION (CLAVE, VALOR) VALUES
('nombre_colegio', 'Heroes del Pacifico'),
('San Martin de Porres', 'Av. Peru'),
('telefono', '988111223'),
('correo', 'heroespacifico@edu.pe'),
('fecha_escolar', '2025');

